services:
  app:
    mem_limit: 2g
    cpus: 2
    "build": {
        "dockerfile": "Dockerfile"
    }
    volumes:
      - ../:/var/www/html  # On remonte d'un niveau pour accéder au projet
      - ~/.ssh:/root/.ssh:ro # Remonte la clé SSH dans le devcontainer
      - ./php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/99-xdebug.ini
    command: >
      sh -c "(command -v apt-get >/dev/null 2>&1 && \
            apt-get update && apt-get install -y unzip curl default-mysql-client) || \
           (command -v apk >/dev/null 2>&1 && \
            apk add --no-cache unzip curl mysql-client) &&
          curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer &&
          chmod -R 777 /var/www/html &&
          docker-php-ext-install pdo pdo_mysql &&
          eval $(ssh-agent -s) && ssh-add ~/.ssh/id_rsa || true &&
          php-fpm"
    environment:
      XDEBUG_MODE: "debug"
      XDEBUG_CONFIG: "client_host=host.docker.internal client_port=9003"
      PHP_IDE_CONFIG: "serverName=docker"

  web:
    image: nginx:alpine
    volumes:
      - ../:/var/www/html  # On remonte d'un niveau pour accéder au projet
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "8000:80"

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: symfony
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"  # Garder le port comme dans ton fichier initial, ou changer si nécessaire
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - db
